#Makefile for libvirt-test-API

XML_LANG      = en-US
FORMATS       = html,pdf
DOCNAME       = libvirt-test-API
PRODUCT       = Libvirt
BRAND         = common
CONFIDENTIAL  = 0

all:
	publican build --langs $(XML_LANG) --formats $(FORMATS)

